### PR TITLE
doc: document new usage patterns

### PR DESCRIPTION
**Pull request by LemonBreezes**
This commit documents how to use i3bar.el as a fallback status bar and how to use it with EXWM.

### CODE REVIEW

**Comment by Stebalien** [comment]
Oh, sorry, I should have been more specific. I meant to ask you to add a section with a working i3 status config (just that first part and any other options you might need to set).

The `tab-bar` stuff is already documented, and the rest is pretty specific to your config (doom-emacs, checking for other bars, etc.). I don't want to add too much to the README, otherwise it becomes hard to find the information you actually need.

**Comment by LemonBreezes** [comment]
> Oh, sorry, I should have been more specific. I meant to ask you to add a section with a working i3 status config (just that first part and any other options you might need to set).
> 
> The `tab-bar` stuff is already documented, and the rest is pretty specific to your config (doom-emacs, checking for other bars, etc.). I don't want to add too much to the README, otherwise it becomes hard to find the information you actually need.

Oh. I haven't used it much beyond getting those things working. I've been using polybar and haven't had to use Emacs on Windows lately.

**Comment by Stebalien** [comment]
Np. I've added the minimal i3status config to the readme in https://github.com/Stebalien/i3bar.el/pull/11/files.

**Comment by Stebalien** [comment]
But thanks for testing it!

**Pull request closed without merging**
